baseURL = "https://forkyfork.com/"
languageCode = "en-GB"
title = "forkyfork"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Johan Holmberg"
    description = "When one fork isn't enough"
    githubUsername = "jvholmberg"
    accent = "red"
    showBorder = true
    backgroundColor = "#fff"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "markdown"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://www.instagram.com/jonish92"
    name = "instagram"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/JohanHolmberg14"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://github.com/jvholmberg"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/johan-holmberg-70044bb6"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "mailto:johan@forkyfork.com"
    name = "envelope-o"
    weight = 5